# .streamlit/secrets.toml
COLD_EMAIL_API_KEY = "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"
COLD_EMAIL_API_BASE_URL = "https://careers.nike.com/software-engineer-i-backend-itc/job/R-68107"

